In [3]:
import numpy as np
arr=np.array([1,2,3,np.nan,5])
print("ignore NaN:",np.nanmean(arr))
print("sum:",np.sum(arr))
print("std ignoring NaN:",np.std(arr[~np.isnan(arr)]))

ignore NaN: 2.75
sum: nan
std ignoring NaN: 1.479019945774904


In [4]:
#replace NaN
import numpy as np
arr=np.array([1,np.nan,3,4,5])
print("replace NaN with 0:",np.where(np.isnan(arr),0,arr))

replace NaN with 0: [1. 0. 3. 4. 5.]


In [1]:
#universal functions ufuncs()
import numpy as np
arr=np.array([1.5,2.9,9.8])
print(arr.astype(np.int32))
arr=np.array([1,2,4,4])
print(arr.astype(np.float64))
arr=np.array([32,534,452,11,988])
print(arr.astype(str))
arr=np.array([11,00,1,0,0])
print(arr.astype(bool))
arr=np.array([ True,False,True,False,False])
print(arr.astype(np.int32))
arr=np.array([1.5,2.9,6.8,4.8])
print(arr.astype(np.complex128))
print(arr.astype(np.int8)) #allocating less space or converting to less space
arr = np.array(["10", "20", "30"])
print(arr.astype(np.int32))


[1 2 9]
[1. 2. 4. 4.]
['32' '534' '452' '11' '988']
[ True False  True False False]
[1 0 1 0 0]
[1.5+0.j 2.9+0.j 6.8+0.j 4.8+0.j]
[1 2 6 4]
[10 20 30]
