In [ ]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
print("Element at [0,1]:",arr[0,1])
print("First row:",arr[0, :])

Element at [0,1]: 2
First row: [1 2 3]


In [9]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
print("First row:",arr[:, 1:])

First row: [[2 3]
 [5 6]]


In [11]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
print("First row:",arr[:, 1:])
arr[0,0]=100
print("modify:",arr)

First row: [[2 3]
 [5 6]]
modify: [[100   2   3]
 [  4   5   6]]


In [19]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
print("First row:",arr[:, 1:])
arr[1,1]=33
print("modify:\n",arr)

First row: [[2 3]
 [5 6]]
modify:
 [[ 1  2  3]
 [ 4 33  6]]



1️⃣Create a NumPy array of strings: ["apple", "banana", "cherry"]. Convert all strings to uppercase.

2️⃣ Replace the letter "a" with "@" in each element of the array: ["cat", "bat", "rat"].

3️⃣ Find the length of each string in the array: ["hello", "world", "numpy", "strings"].

4️⃣ Check whether each element in ["hello", "hey", "hi", "hola"] starts with "h".

5️⃣ Concatenate two arrays of strings: ["good", "nice"] and ["morning", "day"].

6️⃣ Remove the first character from each string in the array: ["apple", "banana", "cherry"].

7️⃣ Split each string in the array ["a,b,c", "d,e,f", "g,h,i"] by comma.

8️⃣ Count how many times the letter "a" appears in each element of ["banana", "apple", "avocado"].

9️⃣ Check if the substring "on" exists in each string of ["python", "java", "c++", "go"].

🔟 Add the suffix "_fruit" to each element in ["apple", "banana", "cherry"].



Common NumPy string methods (numpy.char):

np.char.upper()	np.char.upper(['abc', 'def']) → ['ABC', 'DEF']	Converts all characters to uppercase

np.char.lower()	np.char.lower(['ABC', 'DEF']) → ['abc', 'def']	Converts all characters to lowercase

np.char.capitalize()	np.char.capitalize(['apple', 'banana']) → ['Apple', 'Banana']	Capitalizes first letter

np.char.title()	np.char.title(['hello world']) → ['Hello World']	Capitalizes first letter of each word

np.char.swapcase()	np.char.swapcase(['Hello']) → ['hELLO']	Swaps case (upper ↔ lower)

np.char.strip()	np.char.strip([' apple ']) → ['apple']	Removes whitespace from both ends

np.char.lstrip()	np.char.lstrip([' apple']) → ['apple']	Removes leading whitespace

np.char.rstrip()	np.char.rstrip(['apple ']) → ['apple']	Removes trailing whitespace

np.char.replace()	np.char.replace(['cat'], 'a', '@') → ['c@t']	Replaces substring

np.char.add()	np.char.add(['a', 'b'], ['x', 'y']) → ['ax', 'by']	Element-wise string concatenation

np.char.multiply()	np.char.multiply(['a', 'b'], 3) → ['aaa', 'bbb']	Repeats each 

np.char.center()	np.char.center(['hi'], 5, '*') → ['*hi*']	Centers string with padding

np.char.ljust()	np.char.ljust(['hi'], 4, '*') → ['hi**']	Left-justifies string with padding

np.char.rjust()	np.char.rjust(['hi'], 4, '*') → ['**hi']	Right-justifies string with padding

np.char.zfill()	np.char.zfill(['5'], 3) → ['005']	Pads string on the left with zeros

np.char.find()	np.char.find(['apple'], 'p') → [1]	Returns lowest index of substring

np.char.count()	np.char.count(['apple'], 'p') → [2]	Counts occurrences of substring

np.char.startswith()	np.char.startswith(['apple'], 'a') → [True]	Checks if string starts with substring

np.char.endswith()	np.char.endswith(['apple'], 'e') → [True]	Checks if string ends with substring

np.char.split()	np.char.split(['a,b,c'], ',') → [['a', 'b', 'c']]	Splits string into list

In [ ]:
import numpy as np
l=np.array(["apple","banana","cherry"])
print(np.char.upper(l))

['APPLE' 'BANANA' 'CHERRY']


In [26]:
import numpy as np
b=np.char.replace(["cat", "bat", "rat"],"a","@")
print(b)

['c@t' 'b@t' 'r@t']


In [30]:
import numpy as np
z=np.array(["hello", "world", "numpy", "strings"])
x=np.char.str_len(z)
print(x)

[5 5 5 7]
